base_api_encryption_key: XXXXXXXXXX
base_ota_password: XXXXXXXXXX
base_web_server_username: XXXXXXXXXX
base_web_server_password: XXXXXXXXXX
base_wifi_ssid: XXXXXXXXXX
base_wifi_password: XXXXXXXXXX
base_wifi_ap_password: XXXXXXXXXX
