substitutions:
  device_name: dressingroom-desk
  friendly_name: "Dressing Room - Desk"
  comment: "${friendly_name} (Gosund P1 Mod)"
  default_update_interval: 60s
  powermeter_update_interval: 10s

<<: !include boards/esp8285.yaml
<<: !include components/wifi.yaml
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/web_server.yaml
<<: !include components/time.yaml

logger:
  baud_rate: 0
  logs:
    adc: INFO

status_led:
  pin:
    number: GPIO02
    inverted: True

binary_sensor:
  - !include common/binary_sensor/status.yaml
  - platform: gpio
    id: button_main_id
    internal: True
    pin:
      number: GPIO16
    on_press:
      - switch.toggle: switch_usb_id
  - platform: template
    id: button_1_id
    internal: true
    on_press:
      - switch.toggle: switch_1_id
    filters:
      - delayed_off: 100ms
  - platform: template
    id: button_2_id
    internal: true
    on_press:
      - switch.toggle: switch_2_id
    filters:
      - delayed_off: 100ms
  - platform: template
    id: button_3_id
    internal: true
    on_press:
      - switch.toggle: switch_3_id
    filters:
      - delayed_off: 100ms

switch:
  - platform: gpio
    pin: GPIO14
    id: switch_1_id
    name: "${device_name}_switch01"
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:power-socket-eu
  - platform: gpio
    pin: GPIO12
    id: switch_2_id
    name: "${device_name}_switch02"
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:power-socket-eu
  - platform: gpio
    pin: GPIO13
    id: switch_3_id
    name: "${device_name}_switch03"
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:power-socket-eu
  - platform: gpio
    pin: GPIO05
    id: switch_usb_id
    name: "${device_name}_switchusb"
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:power-socket-eu
    inverted: yes

uart:
  rx_pin: GPIO03
  #tx_pin: GPIO01
  baud_rate: 4800

dallas:
  - pin: GPIO04

sensor:
  - platform: dallas
    address: 0x9D3C01D607A18028
    name: ${device_name}_temperature
    device_class: temperature
    filters:
      - offset: 2.0
  - platform: cse7766
    current:
      name: ${device_name}_current
      icon: mdi:current-ac
      device_class: current
      filters:
        - throttle_average: ${powermeter_update_interval}
        - multiply: 0.993793
    voltage:
      name: ${device_name}_voltage
      icon: mdi:flash-circle
      device_class: voltage
      filters:
        - throttle_average: ${powermeter_update_interval}
        - multiply: 2.410403
    power:
      id: power_id
      name: ${device_name}_power
      icon: mdi:flash-outline
      device_class: power
      filters:
        - throttle_average: ${powermeter_update_interval}
        - multiply: 2.438610
    energy:
      name: ${device_name}_energy
      filters:
        - throttle: ${powermeter_update_interval}
    apparent_power:
      name: ${device_name}_apparentpower
      filters:
        - throttle_average: ${powermeter_update_interval}
    power_factor:
      name: ${device_name}_powerfactor
      filters:
        - throttle_average: ${powermeter_update_interval}
  - <<: !include sensors/electricity/total_daily_energy.yaml
    power_id: power_id
  - platform: adc
    pin: GPIO17
    id: gpio17
    internal: true
    update_interval: 0.1s
    filters:
      - lambda: |-
          if (x >= 0.60 && x < 0.90) {
            id(button_1_id).publish_state(true);
          } else if (x >= 0.30 && x < 0.60) {
            id(button_2_id).publish_state(true);
          }
          else if (x > 0.10 && x < 0.30) {
            id(button_3_id).publish_state(true);
          } else {
            id(button_1_id).publish_state(false);
            id(button_2_id).publish_state(false);
            id(button_3_id).publish_state(false);
          }
          return{};
  - !include sensors/core/wifi_signal.yaml
