substitutions:
  device_name: f0_g_hub
  friendly_name: F0 G Hub
  comment: "Floor 0 - Garage - Hub (NodeMCU ESP32S)"
  default_update_interval: 60s
  
esphome:
  name: ${device_name}
  platform: ESP32
  board: nodemcu-32s
  comment: ${comment}

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml
<<: !include common/wifi.yaml

i2c:
  - sda: GPIO21
    scl: GPIO22

sensor:
  - !include common/sensor/bme280.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

status_led:
  pin: GPIO2
