substitutions:
  device_name: f0_k_hub
  friendly_name: "F0 K Hub"
  comment: "Floor 0 - Kitchen - Hub (NodeMCU ESP32S)"
  default_update_interval: 60s

esphome:
  name: ${device_name}
  platform: ESP32
  board: nodemcu-32s
  comment: ${comment}

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml
<<: !include common/wifi.yaml

sensor:
  - platform: dht
    pin: GPIO32
    model: AM2302
    temperature:
      name: ${friendly_name} Temperature
      id: ${device_name}_temperature
    humidity:
      name: ${friendly_name} Humidity
      id: ${device_name}_humidity
    update_interval: ${default_update_interval}

binary_sensor:
  - !include common/binary_sensor/status.yaml
  - platform: gpio
    pin:
      number: GPIO25
    id: ${device_name}_button
    name: ${friendly_name} Button
    filters:
      - delayed_on: 25ms
      - delayed_off: 2000ms
    on_press:
      - switch.turn_on: ${device_name}_switch

switch:
  - platform: gpio
    pin: GPIO27
    id: relay
  - platform: template
    id: ${device_name}_mute
    name: ${friendly_name} Mute
    icon: mdi:volume-mute
    optimistic: true
    turn_on_action:
      then:
        switch.turn_off: ${device_name}_switch
  - platform: template
    id: ${device_name}_switch
    name: ${friendly_name} Switch
    icon: mdi:bell
    lambda: 'return id(relay).state;'
    turn_on_action:
      then:
        if:
          condition:
            switch.is_off: ${device_name}_mute
          then:
            - switch.turn_on: relay
            - delay: 100ms
            - switch.turn_off: relay
    turn_off_action:
      then:
        switch.turn_off: relay

status_led:
  pin: GPIO2
