substitutions:
  device_name: garage_hub
  friendly_name: Garage Hub
  comment: "Floor 0 - Garage - Hub (NodeMCU ESP32S)"
  wifi_manual_ip_static_ip: !secret garage_hub_wifi_manual_ip_static_ip
  default_update_interval: 60s

packages:
  board: !include boards/nodemcu-32s.yaml
  wifi: !include components/wifi.yaml

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

i2c:
  - sda: GPIO21
    scl: GPIO22

sensor:
  - !include common/sensor/bme280.yaml
  - !include sensors/core/wifi_signal.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

status_led:
  pin: GPIO2
