substitutions:
  device_name: "groundfloorhallway-energymeter"
  friendly_name: "Ground Floor Hallway - Energy Meter"
  comment: "${friendly_name} (NodeMCU ESP32S)"
  default_update_interval: 60s

<<: !include boards/nodemcu-32s.yaml
<<: !include
  file: components/wifi.yaml
  vars:
    manual_ip_static_ip: !secret groundfloorhallway-energymeter_wifi_manual_ip_static_ip
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml
<<: !include components/time.yaml

uart:
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 9600
  #stop_bits: 2

sensor:
  - platform: pzemac
    id: pzemac_01
    current:
      name: "${device_name}_current"
    voltage:
      name: "${device_name}_voltage"
    energy:
      name: "${device_name}_energy"
    power:
      id: power_id
      name: "${device_name}_power"
    frequency:
      name: "${device_name}_frequency"
    power_factor:
      name: "${device_name}_powerfactor"
    update_interval: 1s
  - <<: !include sensors/electricity/total_daily_energy.yaml
    power_id: power_id
  - !include sensors/core/wifi_signal.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

button:
  - platform: template
    name: "${device_name}_resetenergy"
    icon: "mdi:restart"
    on_press:
      then:
        - pzemac.reset_energy: pzemac_01

status_led:
  pin: GPIO2
