substitutions:
  device_name: home_heater
  friendly_name: Home Heater
  comment: "Home - Heater (Sonoff Basic R2 Dry Contact Mod)"
  wifi_manual_ip_static_ip: !secret home_heater_wifi_manual_ip_static_ip

packages:
  board: !include boards/esp01_1m.yaml
  wifi: !include components/wifi.yaml

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: ${device_name}_button
    internal: True
    on_press:
      - switch.toggle: ${device_name}_switch
  - !include common/binary_sensor/status.yaml

status_led:
  pin:
    number: GPIO13
    inverted: yes

switch:
  - platform: gpio
    pin: GPIO12
    id: ${device_name}_switch
    name: ${friendly_name} Switch
