substitutions:
  device_name: home-heater
  friendly_name: "Home - Heater"
  comment: "${friendly_name} (Sonoff Basic R2 Dry Contact Mod)"
  default_update_interval: 60s

packages:
  board: !include boards/esp01_1m.yaml
<<: !include
  file: components/wifi.yaml
  vars:
    manual_ip_static_ip: !secret home-heater_wifi_manual_ip_static_ip
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button_id
    internal: True
    on_press:
      - switch.toggle: switch_id
  - !include common/binary_sensor/status.yaml

sensor:
  - !include sensors/core/wifi_signal.yaml

status_led:
  pin:
    number: GPIO13
    inverted: yes

switch:
  - platform: gpio
    pin: GPIO12
    id: switch_id
    name: ${friendly_name} Switch
