substitutions:
  device_name: kidsbedroom_hub
  friendly_name: KidsBedroom Hub
  comment: "Kids Bedroom - Hub (NodeMCU ESP8266)"
  wifi_manual_ip_static_ip: !secret kidsbedroom_hub_wifi_manual_ip_static_ip
  default_update_interval: 60s

esphome:
  name: ${device_name}
  platform: ESP8266
  board: nodemcuv2
  comment: ${comment}

packages:
  wifi: !include components/wifi.yaml

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

i2c:
  - sda: D2
    scl: D1

sensor:
  - !include common/sensor/bme280.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

status_led:
  pin:
    number: D0
    inverted: True
