substitutions:
  device_name: kidsbedroom-hub
  friendly_name: "Kids Bedroom - Hub"
  comment: "${friendly_name} (NodeMCU ESP8266)"
  default_update_interval: 60s

<<: !include boards/nodemcuv2.yaml
<<: !include
  file: components/wifi.yaml
  vars:
    manual_ip_static_ip: !secret kidsbedroom-hub_wifi_manual_ip_static_ip
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

i2c:
  - sda: D2
    scl: D1

sensor:
  - !include common/sensor/bme280.yaml
  - !include sensors/core/wifi_signal.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

status_led:
  pin:
    number: D0
    inverted: True
