substitutions:
  device_name: kidsbedroom-nightstand
  friendly_name: "Kids Bedroom - Nightstand"
  comment: "${friendly_name} (NodeMCU ESP32S)"
  default_update_interval: 60s

packages:
  board: !include boards/nodemcu-32s.yaml
<<: !include
  file: components/wifi.yaml
  vars:
    manual_ip_static_ip: !secret kidsbedroom-nightstand_wifi_manual_ip_static_ip
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml
<<: !include components/time.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

sensor:
  - !include sensors/core/wifi_signal.yaml

sun:
  latitude: !secret sun_latitude
  longitude: !secret sun_longitude
  on_sunrise:
    then:
      if:
        condition:
          switch.is_on: autoswitch_id
        then:
          light.turn_off: light_id
  on_sunset:
    then:
      if:
        condition:
          switch.is_on: autoswitch_id
        then:
          light.turn_on: light_id

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO23
    num_leds: 3
    rgb_order: GRB
    id: light_id
    name: ${friendly_name} Light

switch:
  - platform: template
    name: ${friendly_name} - AutoSwitch
    id: autoswitch_id
    optimistic: True
    restore_state: True

status_led:
  pin: GPIO2

text_sensor:
  - platform: sun
    name: ${friendly_name} - NextTurnOff
    type: sunrise
  - platform: sun
    name: ${friendly_name} - NextTurnOn
    type: sunset
