substitutions:
  device_name: kidsbedroom-hub
  friendly_name: "Kids Bedroom - Hub"
  comment: "${friendly_name} (NodeMCU ESP8266)"
  default_update_interval: 60s

<<: !include boards/nodemcuv2.yaml
<<: !include components/api.yaml
<<: !include components/captive_portal.yaml
<<: !include components/logger.yaml
<<: !include components/ota/esphome.yaml
<<: !include components/safe_mode.yaml
<<: !include components/web_server.yaml
<<: !include components/wifi.yaml

i2c:
  - sda: D2
    scl: D1

sensor:
  - <<: !include components/sensor/bme280.yaml
  - <<: !include components/sensor/wifi_signal.yaml

binary_sensor:
  - <<: !include components/binary_sensor/status.yaml

status_led:
  pin:
    number: D0
    inverted: True
