substitutions:
  device_name: kitchen_dishwasher
  friendly_name: Kitchen Dishwasher
  comment: "Kitchen - Dishwasher (Plug Blitzwolf SHP2 V2.3)"
  wifi_manual_ip_static_ip: !secret kitchen_dishwasher_wifi_manual_ip_static_ip

packages:
  board: !include boards/esp8285.yaml
  time: !include components/time.yaml
  wifi: !include components/wifi.yaml

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

binary_sensor:
  - platform: gpio
    id: ${device_name}_button
    internal: True
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: ${device_name}_switch
  - !include common/binary_sensor/status.yaml

switch:
  - platform: gpio
    id: ${device_name}_switch
    name: ${friendly_name} Switch
    restore_mode: RESTORE_DEFAULT_OFF
    pin: GPIO14
    on_turn_on:
      - switch.turn_on: ${device_name}_blue_led
    on_turn_off:
      - switch.turn_off: ${device_name}_blue_led

  - platform: gpio
    id: ${device_name}_blue_led
    internal: True
    restore_mode: RESTORE_DEFAULT_OFF
    pin:
      number: GPIO01
      inverted: True

status_led:
  pin:
    number: GPIO13
    inverted: True

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current:
      id: ${device_name}_current
      name: ${friendly_name} Current
      icon: mdi:current-ac
      unit_of_measurement: A
      filters:
        - multiply: 0.829134
    voltage:
      id: ${device_name}_voltage
      name: ${friendly_name} Voltage
      icon: mdi:flash-circle
      unit_of_measurement: V
      filters:
        - multiply: 0.402105
    power:
      id: ${device_name}_power
      name: ${friendly_name} Power
      icon: mdi:flash-outline
      unit_of_measurement: W
      filters:
        - multiply: 0.177739
    change_mode_every: 1
    update_interval: 10s
  - <<: !include sensors/electricity/total_daily_energy.yaml
    power_id: ${device_name}_power
