substitutions:
  device_name: "kitchen-fridgeplug"
  friendly_name: "Kitchen - Fridge Plug"
  comment: "${friendly_name} (Plug Blitzwolf SHP2 V2.3)"
  default_update_interval: 60s

<<: !include boards/esp8285.yaml
<<: !include
  file: components/wifi.yaml
  vars:
    manual_ip_static_ip: !secret kitchen-fridgeplug_wifi_manual_ip_static_ip
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml
<<: !include components/time.yaml

binary_sensor:
  - platform: gpio
    id: button_id
    internal: True
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: switch_id
  - !include common/binary_sensor/status.yaml

switch:
  - platform: gpio
    id: switch_id
    name: ${device_name}_switch
    restore_mode: RESTORE_DEFAULT_ON
    pin: GPIO14
    on_turn_on:
      - switch.turn_on: blue_led_id
    on_turn_off:
      - switch.turn_off: blue_led_id

  - platform: gpio
    id: blue_led_id
    internal: True
    restore_mode: RESTORE_DEFAULT_ON
    pin:
      number: GPIO01
      inverted: True

status_led:
  pin:
    number: GPIO13
    inverted: True

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current:
      name: ${device_name}_current
      icon: mdi:current-ac
      unit_of_measurement: A
      filters:
        - multiply: 0.829134
    voltage:
      name: ${device_name}_voltage
      icon: mdi:flash-circle
      unit_of_measurement: V
      filters:
        - multiply: 0.402105
    power:
      id: power_id
      name: ${device_name}_power
      icon: mdi:flash-outline
      unit_of_measurement: W
      filters:
        - multiply: 0.177739
    change_mode_every: 1
    update_interval: 10s
  - <<: !include sensors/electricity/total_daily_energy.yaml
    power_id: power_id
  - !include sensors/core/wifi_signal.yaml
