substitutions:
  device_name: livingroom_aquarium
  friendly_name: "Living Room - Aquarium"
  comment: "${friendly_name} (Gosund P1 Mod)"
  wifi_manual_ip_static_ip: !secret livingroom_aquarium_wifi_manual_ip_static_ip
  default_update_interval: 60s

packages:
  board: !include boards/esp8285.yaml
  time: !include components/time.yaml
  wifi: !include components/wifi.yaml

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/web_server.yaml

logger:
  baud_rate: 0
  logs:
    adc: INFO

status_led:
  pin:
    number: GPIO02
    inverted: True

binary_sensor:
  - !include common/binary_sensor/status.yaml
  - platform: gpio
    id: button_main_id
    internal: True
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: switch_usb_id
  - platform: template
    id: button_1_id
    internal: true
    on_press:
      - switch.toggle: switch_1_id
    filters:
      - delayed_off: 100ms
  - platform: template
    id: button_2_id
    internal: true
    on_press:
      - switch.toggle: switch_2_id
    filters:
      - delayed_off: 100ms
  - platform: template
    id: button_3_id
    internal: true
    on_press:
      - switch.toggle: switch_3_id
    filters:
      - delayed_off: 100ms

switch:
  - platform: restart
    id: restart_id
    name: "${friendly_name} - Restart"
  - platform: gpio
    pin: GPIO14
    id: switch_1_id
    name: "${friendly_name} - Switch 1"
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:power-socket-eu
  - platform: gpio
    pin: GPIO12
    id: switch_2_id
    name: "${friendly_name} - Switch 2"
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:power-socket-eu
  - platform: gpio
    pin: GPIO13
    id: switch_3_id
    name: "${friendly_name} - Switch 3"
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:power-socket-eu
  - platform: gpio
    pin: GPIO05
    id: switch_usb_id
    name: "${friendly_name} - Switch USB"
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:power-socket-eu
    inverted: yes

uart:
  rx_pin: GPIO03
  #tx_pin: GPIO01
  baud_rate: 4800

dallas:
  - pin: GPIO04

sensor:
  - platform: dallas
    address: 0x9D3C01D607A18028
    name: ${friendly_name} - Temperature
    device_class: temperature
    filters:
      - offset: 2.0
  - platform: cse7766
    current:
      name: ${friendly_name} - Current
      icon: mdi:current-ac
      device_class: current
      filters:
        - multiply: 0.993793
    voltage:
      name: ${friendly_name} - Voltage
      icon: mdi:flash-circle
      device_class: voltage
      filters:
        - multiply: 2.410403
    power:
      id: power_id
      name: ${friendly_name} - Power
      icon: mdi:flash-outline
      device_class: power
      filters:
        - multiply: 2.438610
    update_interval: 10s
  - <<: !include sensors/electricity/total_daily_energy.yaml
    power_id: power_id
  - platform: adc
    pin: GPIO17
    id: gpio17
    internal: true
    update_interval: 0.1s
    filters:
      - lambda: |-
          if (x >= 0.60 && x < 0.90) {
            id(button_1_id).publish_state(true);
          } else if (x >= 0.30 && x < 0.60) {
            id(button_2_id).publish_state(true);
          }
          else if (x > 0.10 && x < 0.30) {
            id(button_3_id).publish_state(true);
          } else {
            id(button_1_id).publish_state(false);
            id(button_2_id).publish_state(false);
            id(button_3_id).publish_state(false);
          }
          return{};
  - !include sensors/core/wifi_signal.yaml
