substitutions:
  device_name: livingroom_hub
  friendly_name: LivingRoom Hub
  miflora_device_name: livingroom_miflora
  miflora_friendly_name: "LivingRoom MiFlora"
  comment: "Floor 0 - Living Room - Hub (NodeMCU ESP32S)"
  default_update_interval: 60s

esphome:
  name: ${device_name}
  platform: ESP32
  board: nodemcu-32s
  comment: ${comment}

wifi:
  ssid: !secret base_wifi_ssid
  password: !secret base_wifi_password
  power_save_mode: none
  fast_connect: true
  manual_ip:
    static_ip: !secret livingroom_hub_wifi_manual_ip_static_ip
    subnet: !secret base_wifi_manual_ip_subnet
    gateway: !secret base_wifi_manual_ip_gateway

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

i2c:
  - sda: GPIO21
    scl: GPIO22

esp32_ble_tracker:

sensor:
  - !include common/sensor/bme280.yaml
  - platform: xiaomi_hhccjcy01
    mac_address: !secret livingroom_miflora_mac
    temperature:
      name: ${miflora_friendly_name} Temperature
      id: ${miflora_device_name}_temperature
    moisture:
      name: ${miflora_friendly_name} Moisture
      id: ${miflora_device_name}_moisture
    illuminance:
      name: ${miflora_friendly_name} Brightness
      id: ${miflora_device_name}_brightness
    conductivity:
      name: ${miflora_friendly_name} Conductivity
      id: ${miflora_device_name}_conductivity
    battery_level:
      name: ${miflora_friendly_name} Battery
      id: ${miflora_device_name}_battery

binary_sensor:
  - !include common/binary_sensor/status.yaml

status_led:
  pin: GPIO2
