substitutions:
  device_name: m_plug
  friendly_name: "M Plug"
  comment: "Mobility - Plug (Plug AWOW EU3S)"
  current_res: "0.00221"
  voltage_div: "955"

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  comment: ${comment}

time:
  - platform: homeassistant
    id: homeassistant_time

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml
<<: !include common/wifi.yaml
    
binary_sensor:
  - platform: gpio
    id: ${device_name}_button
    internal: True
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: ${device_name}_switch
  - !include common/binary_sensor/status.yaml

switch:
  - platform: gpio
    id: ${device_name}_switch
    name: ${friendly_name} Switch
    restore_mode: RESTORE_DEFAULT_OFF
    pin: GPIO15
    on_turn_on:
      - switch.turn_on: ${device_name}_led
    on_turn_off:
      - switch.turn_off: ${device_name}_led

  - platform: gpio
    id: ${device_name}_led
    internal: True
    restore_mode: RESTORE_DEFAULT_OFF
    pin: 
      number: GPIO02
      inverted: True

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      id: ${device_name}_amperage
      name: ${friendly_name} Amperage
      icon: mdi:current-ac
      unit_of_measurement: A
    voltage:
      id: ${device_name}_voltage
      name: ${friendly_name} Voltage
      icon: mdi:flash-circle
      unit_of_measurement: V
    power:
      id: ${device_name}_wattage
      name: ${friendly_name} Wattage
      icon: mdi:flash-outline
      unit_of_measurement: W
    change_mode_every: 8
    update_interval: 10s

  - platform: total_daily_energy
    id: ${device_name}_total_daily_energy
    name: ${friendly_name} Total Daily Energy
    icon: mdi:circle-slice-3
    power_id: ${device_name}_wattage
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
