substitutions:
  device_name: masterbedroom-bedlamp
  friendly_name: "Master Bedroom - Bed Lamp"
  comment: "${friendly_name} (NodeMCU ESP32S)"
  default_update_interval: 60s

<<: !include boards/nodemcu-32s.yaml
<<: !include
  file: components/wifi.yaml
  vars:
    manual_ip_static_ip: !secret masterbedroom-bedlamp_wifi_manual_ip_static_ip
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

sensor:
  - !include sensors/core/wifi_signal.yaml

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO23
    num_leds: 3
    rgb_order: GRB
    id: light_id
    name: ${device_name}_light

status_led:
  pin: GPIO2
