substitutions:
  device_name: masterbedroom-bedlamp
  friendly_name: "Master Bedroom - Bed Lamp"
  comment: "${friendly_name} (NodeMCU ESP32S)"
  default_update_interval: 60s

<<: !include boards/nodemcu-32s.yaml
<<: !include components/wifi.yaml
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

sensor:
  - !include sensors/core/wifi_signal.yaml
  - !include common/sensor/internal_temperature.yaml

light:
  - platform: esp32_rmt_led_strip
    chipset: ws2812
    pin: GPIO23
    num_leds: 3
    rmt_channel: 0
    rgb_order: GRB
    id: light_id
    name: ${device_name}_light

status_led:
  pin: GPIO2
