substitutions:
  device_name: masterbedroom-bedlamp
  friendly_name: "Master Bedroom - Bed Lamp"
  comment: "${friendly_name} (NodeMCU ESP32S)"
  default_update_interval: 60s

<<: !include boards/nodemcu-32s.yaml
<<: !include components/api.yaml
<<: !include components/captive_portal.yaml
<<: !include components/logger.yaml
<<: !include components/ota/esphome.yaml
<<: !include components/safe_mode.yaml
<<: !include components/web_server.yaml
<<: !include components/wifi.yaml

binary_sensor:
  - <<: !include components/binary_sensor/status.yaml

sensor:
  - <<: !include components/sensor/internal_temperature.yaml
  - <<: !include components/sensor/wifi_signal.yaml

light:
  - platform: esp32_rmt_led_strip
    chipset: ws2812
    pin: GPIO23
    num_leds: 3
    rmt_channel: 0
    rgb_order: GRB
    id: light_id
    name: ${device_name}_light

status_led:
  pin: GPIO2
