substitutions:
  device_name: office_deskplug
  friendly_name: "Office DeskPlug"
  comment: "Office - Desk Plug (Plug AWOW EU3S)"
  wifi_manual_ip_static_ip: !secret office_deskplug_wifi_manual_ip_static_ip

packages:
  board: !include boards/esp01_1m.yaml
  time: !include components/time.yaml
  wifi: !include components/wifi.yaml

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

binary_sensor:
  - platform: gpio
    id: ${device_name}_button
    internal: True
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: ${device_name}_switch
  - !include common/binary_sensor/status.yaml

switch:
  - platform: gpio
    id: ${device_name}_switch
    name: ${friendly_name} Switch
    restore_mode: RESTORE_DEFAULT_OFF
    pin: GPIO15
    on_turn_on:
      - switch.turn_on: ${device_name}_led
    on_turn_off:
      - switch.turn_off: ${device_name}_led
  - platform: gpio
    id: ${device_name}_led
    internal: True
    restore_mode: RESTORE_DEFAULT_OFF
    pin:
      number: GPIO02
      inverted: True

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current:
      id: ${device_name}_current
      name: ${friendly_name} Current
      icon: mdi:current-ac
      unit_of_measurement: A
      filters:
        - multiply: 0.713100
    voltage:
      id: ${device_name}_voltage
      name: ${friendly_name} Voltage
      icon: mdi:flash-circle
      unit_of_measurement: V
      filters:
        - multiply: 0.404015
    power:
      id: ${device_name}_power
      name: ${friendly_name} Power
      icon: mdi:flash-outline
      unit_of_measurement: W
      filters:
        - multiply: 0.151556
    change_mode_every: 1
    update_interval: 10s
  - <<: !include sensors/electricity/total_daily_energy.yaml
    power_id: ${device_name}_power
