substitutions:
  device_name: office-hub
  friendly_name: "Office - Hub"
  comment: "${friendly_name} (NodeMCU ESP32S)"
  default_update_interval: 60s

<<: !include boards/nodemcu-32s.yaml
<<: !include
  file: components/wifi.yaml
  vars:
    manual_ip_static_ip: !secret office-hub_wifi_manual_ip_static_ip
<<: !include components/bluetooth_proxy.yaml
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

i2c:
  - sda: GPIO21
    scl: GPIO22

sensor:
  - !include common/sensor/bme280.yaml
  - !include sensors/core/wifi_signal.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

status_led:
  pin: GPIO2
