substitutions:
  device_name: office_hub
  friendly_name: Office Hub
  comment: "Office - Hub (NodeMCU ESP32S)"
  wifi_manual_ip_static_ip: !secret office_hub_wifi_manual_ip_static_ip
  default_update_interval: 60s

esphome:
  <<: !include components/esphome.yaml
  platform: ESP32
  board: esp32dev

packages:
  wifi: !include components/wifi.yaml

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

i2c:
  - sda: GPIO21
    scl: GPIO22

sensor:
  - !include common/sensor/bme280.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

status_led:
  pin: GPIO2
