substitutions:
  device_name: "serverroom-hub"
  friendly_name: "Server Room - Hub"
  comment: "${friendly_name} (NodeMCU ESP32S)"
  default_update_interval: 60s

<<: !include boards/nodemcu-32s.yaml
<<: !include components/api.yaml
<<: !include components/bluetooth_proxy.yaml
<<: !include components/captive_portal.yaml
<<: !include components/logger.yaml
<<: !include components/ota/esphome.yaml
<<: !include components/safe_mode.yaml
<<: !include components/web_server.yaml
<<: !include components/wifi.yaml

i2c:
  - sda: GPIO21
    scl: GPIO22

sensor:
  - <<: !include components/sensor/bme280.yaml
  - <<: !include components/sensor/internal_temperature.yaml
  - <<: !include components/sensor/wifi_signal.yaml

binary_sensor:
  - <<: !include components/binary_sensor/status.yaml

status_led:
  pin: GPIO2
