substitutions:
  device_name: test_esp32_01
  friendly_name: "Test ESP32 01"
  comment: "Test - ESP32 - 01 (NodeMCU ESP32S)"
  wifi_manual_ip_static_ip: !secret test_esp32_01_wifi_manual_ip_static_ip
  default_update_interval: 60s

esphome:
  name: ${device_name}
  platform: ESP32
  board: nodemcu-32s
  comment: ${comment}

packages:
  time: !include components/time.yaml
  wifi: !include components/wifi.yaml

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

#logger:
  #baud_rate: 0

uart:
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 9600
  stop_bits: 2

sensor:
  - platform: pzemac
    current:
      name: "PZEM-004T V3 Current"
    voltage:
      name: "PZEM-004T V3 Voltage"
    energy:
      name: "PZEM-004T V3 Energy"
    power:
      id: device_power
      name: "PZEM-004T V3 Power"
    frequency:
      name: "PZEM-004T V3 Frequency"
    power_factor:
      name: "PZEM-004T V3 Power Factor"
    update_interval: 1s
  - <<: !include sensors/electricity/total_daily_energy.yaml
    power_id: device_power

binary_sensor:
  - !include common/binary_sensor/status.yaml

status_led:
  pin: GPIO2
