substitutions:
  device_name: test_esp32cam_01
  friendly_name: "Test ESP32CAM 01"
  comment: "Test - ESP32CAM - 01 (ESP32-CAM)"
  wifi_manual_ip_static_ip: !secret test_esp32cam_01_wifi_manual_ip_static_ip
  default_update_interval: 60s

esphome:
  name: ${device_name}
  platform: ESP32
  board: esp32cam
  comment: ${comment}

packages:
  wifi: !include components/wifi.yaml

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

i2c:
  - sda: GPIO13
    scl: GPIO14

sensor:
  - !include common/sensor/bme280.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

status_led:
  pin:
    number: GPIO33
    inverted: true

output:
  - platform: gpio
    pin: GPIO4
    id: led

light:
  - platform: binary
    name: ${friendly_name} Light
    id: ${device_name}_light
    output: led

switch:
  - platform: restart
    name: ${friendly_name} Restart
    id: ${device_name}_restart

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  name: ${friendly_name} Camera
  id: ${device_name}_camera
