substitutions:
  device_name: test-wt32
  friendly_name: Test - WT32
  comment: "${friendly_name} (WT32)"
  default_update_interval: 60s

esphome:
  <<: !include components/esphome.yaml

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

<<: !include components/ota/esphome.yaml
<<: !include components/safe_mode.yaml
<<: !include components/api.yaml
<<: !include components/logger.yaml
<<: !include components/web_server.yaml

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

binary_sensor:
  - <<: !include components/binary_sensor/status.yaml

sensor:
  - <<: !include components/sensor/internal_temperature.yaml
