substitutions:
  device_name: test-irhub
  friendly_name: Test - IR Hub
  comment: "${friendly_name} (FK-UFO-R1)"
  default_update_interval: 60s

esphome:
  <<: !include components/esphome.yaml
  on_boot:
    priority: 100 # Highest priority, ensures light turns on without delay.
    then:
      - light.turn_on: light_id

<<: !include boards/esp01_1m.yaml
<<: !include components/api.yaml
<<: !include components/captive_portal.yaml
<<: !include components/logger.yaml
<<: !include components/ota/esphome.yaml
<<: !include components/safe_mode.yaml
<<: !include components/web_server.yaml
<<: !include components/wifi.yaml

remote_transmitter:
  pin: GPIO14
  carrier_duty_percent: 33%

remote_receiver:
  pin:
    number: GPIO5
    inverted: True
  dump: raw
#  on_raw:
#    - remote_transmitter.transmit_raw:
#        code: !lambda return x;

binary_sensor:
  - <<: !include components/binary_sensor/status.yaml

sensor:
  - <<: !include components/sensor/wifi_signal.yaml

switch:
  - platform: gpio
    id: switch_id

    restore_mode: RESTORE_DEFAULT_OFF
    pin: GPIO13
    on_turn_on:
      - switch.turn_on: restart_id
  - platform: restart
    id: restart_id
    name: ${device_name}_restart

output:
  - platform: esp8266_pwm
    id: led_id
    pin:
      number: GPIO4
      inverted: True

light:
  - platform: monochromatic
    output: led_id
    id: light_id
