substitutions:
  device_name: test-esp32
  friendly_name: "Test - ESP32"
  comment: "${friendly_name} (NodeMCU ESP32S)"
  default_update_interval: 60s

packages:
  board: !include boards/nodemcu-32s.yaml
<<: !include
  file: components/wifi.yaml
  vars:
    manual_ip_static_ip: !secret test-esp32_wifi_manual_ip_static_ip
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml
<<: !include components/time.yaml

#logger:
#  baud_rate: 0

uart:
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 9600
  stop_bits: 2

sensor:
  - platform: pzemac
    current:
      name: "PZEM-004T V3 - Current"
    voltage:
      name: "PZEM-004T V3 - Voltage"
    energy:
      name: "PZEM-004T V3 - Energy"
    power:
      id: power_id
      name: "PZEM-004T V3 - Power"
    frequency:
      name: "PZEM-004T V3 - Frequency"
    power_factor:
      name: "PZEM-004T V3 - Power Factor"
    update_interval: 1s
  - <<: !include sensors/electricity/total_daily_energy.yaml
    power_id: power_id
  - !include sensors/core/wifi_signal.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

status_led:
  pin: GPIO2
