substitutions:
  device_name: test-esp32cam
  friendly_name: "Test - ESP32CAM"
  comment: "${friendly_name} (ESP32-CAM)"
  default_update_interval: 60s

<<: !include boards/esp32cam.yaml
<<: !include components/api.yaml
<<: !include components/captive_portal.yaml
<<: !include components/logger.yaml
<<: !include components/ota/esphome.yaml
<<: !include components/safe_mode.yaml
<<: !include components/web_server.yaml
<<: !include components/wifi.yaml

i2c:
  - sda: GPIO13
    scl: GPIO14

sensor:
  - <<: !include components/sensor/bme280.yaml
  - <<: !include components/sensor/internal_temperature.yaml
  - <<: !include components/sensor/wifi_signal.yaml

binary_sensor:
  - <<: !include components/binary_sensor/status.yaml

status_led:
  pin:
    number: GPIO33
    inverted: true

output:
  - platform: gpio
    pin: GPIO4
    id: led_id

light:
  - platform: binary
    name: ${device_name}_light
    output: led_id

switch:
  - platform: restart
    name: ${device_name}_restart

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  name: ${device_name}_camera
