substitutions:
  name: test-wt32
  comment: "Test - WT32 (WT32)"
  default_update_interval: 60s

esphome:
  <<: !include components/esphome.yaml

esp32:
  board: wt32-eth01
  framework:
    type: esp-idf

<<: !include components/ota/esphome.yaml
<<: !include components/safe_mode.yaml
<<: !include components/api.yaml
<<: !include components/logger.yaml
<<: !include components/web_server.yaml

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 1
  power_pin: GPIO16

text_sensor:
  - <<: !include components/text_sensor/version.yaml
  - <<: !include components/text_sensor/ethernet_info.yaml

button:
  - <<: !include components/button/restart.yaml

binary_sensor:
  - <<: !include components/binary_sensor/status.yaml

sensor:
  - <<: !include components/sensor/uptime.yaml
  - <<: !include components/sensor/internal_temperature.yaml
