substitutions:
  device_name: test_irhub
  friendly_name: Test - IR Hub
  comment: "${friendly_name} (FK-UFO-R1)"
  wifi_manual_ip_static_ip: !secret test_irhub_wifi_manual_ip_static_ip
  default_update_interval: 60s

esphome:
  on_boot:
    priority: 100 # Highest priority, ensures light turns on without delay.
    then:
      - light.turn_on: light_id

packages:
  board: !include boards/esp01_1m.yaml
  wifi: !include components/wifi.yaml

<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

remote_transmitter:
  pin: GPIO14
  carrier_duty_percent: 33%

remote_receiver:
  pin:
    number: GPIO5
    inverted: True
  dump: raw
#  on_raw:
#    - remote_transmitter.transmit_raw:
#        code: !lambda return x;

binary_sensor:
  - !include common/binary_sensor/status.yaml

sensor:
  - !include sensors/core/wifi_signal.yaml

switch:
  - platform: gpio
    id: switch_id

    restore_mode: RESTORE_DEFAULT_OFF
    pin: GPIO13
    on_turn_on:
      - switch.turn_on: restart_id
  - platform: restart
    id: restart_id
    name: ${friendly_name} - Restart

output:
  - platform: esp8266_pwm
    id: led_id
    pin:
      number: GPIO4
      inverted: True

light:
  - platform: monochromatic
    output: led_id
    id: light_id
