substitutions:
  device_name: "utility-waterheater"
  friendly_name: "Utility - Water Heater"
  comment: "${friendly_name} (Sonoff Basic R2 Dry Contact Mod)"
  default_update_interval: 60s

<<: !include boards/esp01_1m.yaml
<<: !include components/api.yaml
<<: !include components/captive_portal.yaml
<<: !include components/logger.yaml
<<: !include components/ota/esphome.yaml
<<: !include components/safe_mode.yaml
<<: !include components/web_server.yaml
<<: !include components/wifi.yaml

binary_sensor:
  - <<: !include components/binary_sensor/status.yaml
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button_id
    internal: True
    on_press:
      - switch.toggle: switch_id

sensor:
  - <<: !include components/sensor/wifi_signal.yaml

status_led:
  pin:
    number: GPIO13
    inverted: yes

switch:
  - platform: gpio
    pin: GPIO12
    id: switch_id
    name: ${device_name}_switch
