substitutions:
  device_name: utility-washingmachine
  friendly_name: "Utility - Washing Machine"
  comment: "${friendly_name} (Plug AWOW EU3S)"
  default_update_interval: 60s

packages:
  board: !include boards/esp01_1m.yaml
  time: !include components/time.yaml
<<: !include
  file: components/wifi.yaml
  vars:
    manual_ip_static_ip: !secret utility-washingmachine_wifi_manual_ip_static_ip
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/logger.yaml
<<: !include common/web_server.yaml

binary_sensor:
  - platform: gpio
    id: button_id
    internal: True
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: switch_id
  - !include common/binary_sensor/status.yaml

switch:
  - platform: gpio
    id: switch_id
    name: ${friendly_name} - Switch
    restore_mode: RESTORE_DEFAULT_OFF
    pin: GPIO15
    on_turn_on:
      - switch.turn_on: led_id
    on_turn_off:
      - switch.turn_off: led_id

  - platform: gpio
    id: led_id
    internal: True
    restore_mode: RESTORE_DEFAULT_OFF
    pin:
      number: GPIO02
      inverted: True

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current:
      name: ${friendly_name} - Current
      icon: mdi:current-ac
      unit_of_measurement: A
      filters:
        - multiply: 0.746064
    voltage:
      name: ${friendly_name} - Voltage
      icon: mdi:flash-circle
      unit_of_measurement: V
      filters:
        - multiply: 0.420251
    power:
      id: power_id
      name: ${friendly_name} - Power
      icon: mdi:flash-outline
      unit_of_measurement: W
      filters:
        - multiply: 0.159374
    change_mode_every: 1
    update_interval: 10s
  - <<: !include sensors/electricity/total_daily_energy.yaml
    power_id: power_id
  - !include sensors/core/wifi_signal.yaml
