# AI Thinker ESP32-CAM board. Small Camera Module to build little projects.
#
# https://docs.platformio.org/en/latest/boards/espressif32/esp32cam
# http://www.ai-thinker.com/pro_view-24
# https://amzn.to/3mhZa3r
#

---
esphome:
  <<: !include "../components/esphome.yaml"

esp32:
  board: esp32cam
