# Generic ESP8285 board. Used in some already manufactured devices.
#
# https://docs.platformio.org/en/latest/boards/espressif8266/esp8285
#

---
esphome:
  <<: !include "../components/esphome.yaml"

esp8266:
  board: esp8285
