# NodeMCU-32S board. ESP32 Development Module to build little projects.
#
# https://docs.platformio.org/en/latest/boards/espressif32/nodemcu-32s
# https://amzn.to/3svRWtO
#

---
esphome:
  <<: !include "../components/esphome.yaml"

esp32:
  board: nodemcu-32s
